### PR TITLE
Add workflow to deploy to GH pages

### PR DESCRIPTION
**Pull request by CFenner**
This workflow can deploy to GH pages
- on demand 
- on schedule
- on push to main branch

### CODE REVIEW

**Comment by CFenner** [comment]
Data is updated, but page has an old date:

Bildschirmfoto 2024-01-04 um 17 48 49

**Comment by KristjanESPERANTO** [comment]
That's nice! Thank you! I haven't done much with GitHub pages yet, I want to read up on the topic and understand it better before I merge.

**Comment by KristjanESPERANTO** [comment]
> Also the referenced result.md is the static one from the repository, not the generated.

If this file were written to docs, it would have to be updated, wouldn't it?

> Would be nice to see the findings in a popup on the page.

I didn't want to make it too present on the web page for normal users so that it doesn't put them off if a module has a long list. But yes, a popup or something like that is a good idea! I've put it on the to-do list.

**Comment by CFenner** [comment]
> > Also the referenced result.md is the static one from the repository, not the generated.
> 
> If this file were written to docs, it would have to be updated, wouldn't it?

Yes, but the link would also need to change to be relative, to the file in the deployment is used and not the one in the docs folder on the main branch.

**Pull request merged**
